export {default as Navbar} from './Navbar/Navbar.jsx'
export {default as Feature} from './Feature/Feature.jsx'
export {default as Article} from './Article/Article.jsx'
export {default as Brands} from './Brands/Brands.jsx'
export {default as CTA} from './CTA/CTA.jsx'